import React from 'react';
import { PostFrontmatter } from '@/types/post';
import {
  KeyTakeaways,
  ModeToggle,
  FootnoteAside,
  QuickCheck,
  DiagramBlock,
  MistakeList,
  MisconceptionCallout,
  ActionChecklist,
  FAQBlock,
  GlossaryStrip,
  SeeAlsoList,
  TermLink
} from '@/components';

export const metadata: PostFrontmatter = {
  title: "What a Credit Score Actually Measures",
  category: "personal-finance-basics",
  order: 23,
  subtopic: "credit-and-debt",
  tags: ["credit score", "FICO", "credit history", "personal finance basics", "financial literacy"],
  date: "2026-08-22",
  updated: "2026-08-22",
  lastReviewed: "2026-08-22",
  excerpt: "A credit score isn't a measure of income or wealth — it's a statistical estimate of how likely you are to repay debt on time, built almost entirely from your payment history and how much of your available credit you use.",
  summary: "A credit score is a three-digit number, typically 300-850 on the FICO scale, generated by a statistical model that estimates the likelihood a borrower will repay debt as agreed — weighted mainly by payment history and credit utilization, not income or savings.",
  sources: [
    { label: "Consumer Financial Protection Bureau — What Is a Credit Score?", url: "https://www.consumerfinance.gov/ask-cfpb/what-is-a-credit-score-en-315/" },
    { label: "myFICO — What's in My FICO Scores", url: "https://www.myfico.com/credit-education/whats-in-your-credit-score" },
    { label: "Federal Trade Commission — Understanding Your Credit", url: "https://consumer.ftc.gov/articles/understanding-your-credit" },
  ],
  seeAlso: [
    "personal-finance-basics/how-credit-reports-work",
    "personal-finance-basics/credit-cards-explained-interest-grace-periods-minimum-payments",
    "personal-finance-basics/good-debt-vs-bad-debt-factual-framing",
  ],
  glossary: [
    {"term":"Credit score","definition":"A three-digit number generated by a statistical model (most commonly FICO or VantageScore) that estimates the likelihood a borrower will repay debt as agreed, based on the contents of their credit report."},
    {"term":"Credit utilization","definition":"The percentage of available revolving credit currently being used — for example, a $500 balance on a $2,000 credit limit is 25% utilization — one of the largest factors in most credit scoring models."},
    {"term":"Payment history","definition":"A record of whether past debt payments were made on time, late, or missed entirely — the single largest weighted factor in the FICO scoring model."}
  ],
  author: {
    slug: "james-h-rivers",
    name: "James H. Rivers",
    credentialLine: "Founder, KnowThisWell",
  },
  youtubeStatus: "scheduled",
  youtubeUrl: "https://www.youtube.com/watch?v=voWrfvnbd00",
  youtubeScheduledAt: "2026-09-07T16:00:00Z",
  draft: false,
};

export default function Post() {
  return (
    <>
      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Key Takeaways</h2>
      <KeyTakeaways
      points={[
      "A credit score is a statistical estimate of repayment likelihood, not a measure of income, savings, or overall wealth — someone with a high income can have a low score, and vice versa.",
      "Per FICO's own published methodology, payment history (35%) and credit utilization (30%) together account for nearly two-thirds of the score — length of credit history, credit mix, and new credit make up the rest.",
      "Scores are generated by private companies (FICO, VantageScore) from the data in your credit reports, not assigned directly by the government or a single central authority.",
      ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">The concept</h2>
      <ModeToggle
      labels={{ plain: "Plain", detailed: "Detailed" }}
      plain={<div className="prose-p">A <TermLink href="/personal-finance-basics/what-a-credit-score-actually-measures">credit score</TermLink> is a three-digit number, most commonly ranging from 300 to 850, that predicts how likely you are to pay back borrowed money on time. It&apos;s calculated from your credit report — a record of your loans, credit cards, and payment history — using a formula built by companies like FICO. Lenders use it to decide whether to approve you for a loan or credit card, and what interest rate to charge.</div>}
      detailed={<div className="prose-p">The most widely used scoring model, FICO, publishes its own approximate factor weighting: <TermLink href="/personal-finance-basics/what-a-credit-score-actually-measures">payment history</TermLink> (35%), amounts owed relative to credit limits — <TermLink href="/personal-finance-basics/what-a-credit-score-actually-measures">credit utilization</TermLink> (30%), length of credit history (15%), credit mix — the variety of account types like credit cards, auto loans, and mortgages (10%), and new credit inquiries (10%). Critically, income, employment status, savings balances, and net worth are not inputs to the score at all — the model only looks at borrowing and repayment behavior recorded on credit reports from the three major bureaus (Equifax, Experian, TransUnion). This is why a high earner with maxed-out credit cards can have a lower score than a modest earner who pays every bill on time.</div>}
      />
      <FootnoteAside>FICO and VantageScore are the two dominant scoring models, and each can produce a somewhat different number from the same credit report, since they weight factors slightly differently and use different score ranges — there is no single universal &quot;your credit score,&quot; only different models&apos; estimates from the same underlying data.</FootnoteAside>

      <p>
      Understanding which factors carry the most weight is what turns &quot;improve your credit score&quot; from vague advice into something with an actual mechanism behind it.
      </p>

      <QuickCheck
      question="Someone earns a high salary and has significant savings, but has missed several credit card payments in the past year. Will their credit score likely be high?"
      options={[
      { text: "Yes — a high income and savings automatically produce a high credit score", correct: false, explanation: "Income and savings are not inputs to standard credit scoring models at all. The score is calculated purely from credit report data — borrowing and repayment behavior — regardless of how much someone earns or has saved." },
      { text: "Likely not — missed payments are the single most heavily weighted factor (about 35% in the FICO model), and income/savings don't factor into the score at all", correct: true, explanation: "Correct. Payment history dominates the score. A pattern of missed payments will pull the score down regardless of the person's income or bank balance, since those simply aren't part of the calculation." },
      { text: "It depends only on their credit utilization, since that's the only factor that matters", correct: false, explanation: "Utilization is a major factor (about 30%), but it isn't the only one — payment history, credit history length, credit mix, and new credit inquiries all contribute too." },
      ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Worked examples</h2>

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 1: Two borrowers with identical income, different scores (baseline case)</h3>
      <div className="prose-p">
      Borrower A and Borrower B both earn $60,000 a year. Borrower A has paid every bill on time for five years and keeps credit card balances below 10% of their limits. Borrower B has the same income but missed three payments last year and regularly carries balances near 90% of their limits. Despite identical income, Borrower A will have a meaningfully higher score — the scoring model never sees their income at all, only the credit report data showing payment reliability and utilization.
      </div>

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 2: Reducing utilization without paying off the full balance (edge case / variation)</h3>
      <div className="prose-p">
      A cardholder has a $4,000 balance on a $5,000 limit card — 80% utilization, well above the commonly cited &quot;under 30%&quot; guideline. Paying the balance down to $1,400 brings utilization to 28%, which alone can produce a noticeable score improvement within one to two billing cycles, even without paying the balance to zero and even if payment history hasn&apos;t changed. Utilization is calculated from the balance reported at a point in time (typically the statement closing date), not from spending behavior throughout the month.
      </div>

      <QuickCheck
      question="Why can paying a credit card balance down (not fully off) still measurably improve a credit score within one or two billing cycles?"
      options={[
      { text: "Because credit scores only update once a year regardless of activity", correct: false, explanation: "Credit reports and scores typically update monthly, as new information is reported by lenders — not on an annual cycle." },
      { text: "Because credit utilization is calculated from the balance reported at a specific point in time (usually the statement closing date), so lowering that reported balance directly lowers the utilization ratio even without a zero balance", correct: true, explanation: "Correct. Utilization doesn't require a zero balance to improve — any reduction in the reported balance-to-limit ratio can move the number, since that ratio is exactly what the scoring model reads." },
      { text: "Paying down a balance has no effect on utilization unless the account is closed", correct: false, explanation: "Closing an account can actually hurt utilization (by reducing total available credit) — reducing the reported balance while keeping the account open is what directly improves the utilization ratio." },
      ]}
      />

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 3: A thin credit file limiting an otherwise strong score (real-world / applied case)</h3>
      <div className="prose-p">
      A 22-year-old with one 8-month-old credit card, no missed payments, and low utilization might still score in the &quot;fair&quot; range rather than &quot;excellent,&quot; despite doing everything right so far. Length of credit history (15% of the FICO model) rewards a longer track record, and a thin file (few accounts, short history) simply hasn&apos;t accumulated enough data for the model to weight favorably yet — this isn&apos;t a penalty for a mistake, it&apos;s a structural limitation of having a short credit history, and it resolves with time and continued on-time payments.
      </div>

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">How it works (visual)</h2>
      <DiagramBlock
      title="Approximate FICO score factor weighting"
      type="comparison"
      svgSrc="/diagrams/personal-finance-basics-what-a-credit-score-actually-measures-fico-weighting.svg"
      altText="A horizontal stacked bar divided into five segments by width, labeled from largest to smallest: Payment History 35%, Amounts Owed (Utilization) 30%, Length of Credit History 15%, Credit Mix 10%, and New Credit 10%, with a caption noting income and savings are not inputs to the model at all."
      />
      <p>
      The two largest segments — payment history and utilization — together make up nearly two-thirds of the score, which is why those two behaviors (paying on time, keeping balances low relative to limits) produce the most noticeable movement in the number.
      </p>

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Common mistakes</h2>
      <MistakeList
      items={[
      { mistake: "Assuming income or savings directly raise a credit score.", fix: "Remember the score is calculated purely from credit report data (borrowing and repayment behavior) — building income or savings doesn't move the number unless it changes how you use and repay credit." },
      { mistake: "Closing an old, unused credit card to 'simplify,' without realizing it can shorten credit history and reduce total available credit.", fix: "Consider keeping old accounts open (especially with no annual fee) even if unused — closing them can raise utilization and reduce average account age, both of which can lower a score." },
      { mistake: "Treating 'FICO score' and 'credit score' as always identical.", fix: "Recognize FICO and VantageScore are separate models that can produce different numbers from the same credit report — check which model a lender is actually using before comparing scores from different sources." },
      ]}
      />
      <MisconceptionCallout
      myth="Checking your own credit score hurts it."
      reality={<p>Checking your own score or report is called a &quot;soft inquiry&quot; and has no effect on the score at all — this is different from a &quot;hard inquiry,&quot; which happens when a lender checks your credit as part of a loan or credit card application, and can cause a small, temporary dip. Consumers are entitled to free access to their own credit reports and scores without penalty.</p>}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">What to do next</h2>
      <ActionChecklist
      items={[
      "Check your own credit report through a free, official channel (in the US, annualcreditreport.com) to see the raw data the score is built from — this is a soft inquiry and doesn't affect your score.",
      "If you carry credit card balances, note your utilization percentage — balance divided by limit — since that single ratio is one of the two biggest score factors.",
      "Avoid closing your oldest credit accounts if you're trying to build score, since account age and total available credit both factor in.",
      "For a real credit-building or debt strategy specific to your situation, talk to a nonprofit credit counselor (NFCC-affiliated organizations are a legitimate free/low-cost starting point) rather than relying on general guidance alone.",
      ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">FAQ</h2>
      <FAQBlock
      items={[
      { question: "What is considered a good credit score?", answer: "On the common 300-850 FICO scale, scores are generally categorized as roughly: 800+ exceptional, 740-799 very good, 670-739 good, 580-669 fair, and below 580 poor — exact bands can vary slightly by lender and scoring model." },
      { question: "Does checking my credit score lower it?", answer: "No. Checking your own score or report is a 'soft inquiry' and has no effect on the score. Only 'hard inquiries' from lenders reviewing an actual credit application can cause a small, temporary dip." },
      { question: "Does income affect my credit score?", answer: "No. Standard credit scoring models like FICO do not use income, employment status, or savings as inputs at all — the score is calculated entirely from credit report data about borrowing and repayment." },
      { question: "How often does a credit score update?", answer: "Typically monthly, as lenders report new account activity (balances, payments) to the credit bureaus — though the exact timing depends on when each individual lender reports." },
      { question: "What hurts a credit score the most?", answer: "Missed or late payments generally cause the most damage, since payment history is the single largest weighted factor (about 35% in the FICO model), followed closely by high credit utilization." },
      ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Related terms</h2>
      <GlossaryStrip terms={metadata.glossary ?? []} />
      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">See also</h2>
      <SeeAlsoList slugs={metadata.seeAlso ?? []} />
    </>
  );
}
