import React from 'react';
import { PostMeta, PostFrontmatter } from '@/types/post';
import {
  KeyTakeaways,
  ModeToggle,
  FootnoteAside,
  QuickCheck,
  DiagramBlock,
  MistakeList,
  MisconceptionCallout,
  EntryCalculator,
  ActionChecklist,
  FAQBlock,
  GlossaryStrip,
  SeeAlsoList,
  TermLink
} from '@/components';

export const metadata: PostFrontmatter = {
  title: "Sequences & Patterns: Arithmetic vs. Geometric, and How to Find Any Term",
  category: "math-numbers",
  order: 22,
  subtopic: "algebra-foundations",
  tags: [
    "sequences",
    "arithmetic sequence",
    "geometric sequence",
    "number patterns",
    "nth term",
    "algebra basics",
  ],
  date: "2026-08-16",
  updated: "2026-08-16",
  lastReviewed: "2026-08-16",
  excerpt: "The difference between arithmetic and geometric sequences, how to find any term without listing every one before it, and where each type shows up in real life.",
  summary: "A sequence is an ordered list of numbers following a rule; arithmetic sequences add a constant difference between terms, while geometric sequences multiply by a constant ratio.",
  sources: [
    { label: "Encyclopaedia Britannica — Arithmetic Sequence", url: "https://www.britannica.com/science/arithmetic-sequence" },
    { label: "Encyclopaedia Britannica — Geometric Sequence", url: "https://www.britannica.com/science/geometric-sequence" },
    { label: "MathWorld (Wolfram) — Arithmetic Sequence", url: "https://mathworld.wolfram.com/ArithmeticSequence.html" },
    { label: "MathWorld (Wolfram) — Geometric Sequence", url: "https://mathworld.wolfram.com/GeometricSequence.html" },
  ],
  seeAlso: [
    "math-numbers/what-is-algebra-variables-expressions",
    "math-numbers/linear-equations-explained",
    "math-numbers/solving-simple-equations",
    "math-numbers/factors-and-multiples",
  ],
  glossary: [
    { term: "Sequence", definition: "An ordered list of numbers, called terms, generated by following a consistent rule." },
    { term: "Term", definition: "A single number's position and value within a sequence — the 1st term, 2nd term, and so on." },
    { term: "Arithmetic sequence", definition: "A sequence where each term is found by adding a constant amount, called the common difference, to the previous term." },
    { term: "Common difference", definition: "The fixed amount added between consecutive terms of an arithmetic sequence; it can be positive, negative, or zero." },
    { term: "Geometric sequence", definition: "A sequence where each term is found by multiplying the previous term by a constant amount, called the common ratio." },
    { term: "Common ratio", definition: "The fixed factor each term of a geometric sequence is multiplied by to get the next term." },
    { term: "nth term formula", definition: "A direct formula that computes any term of a sequence from its position (n) alone, without listing every term before it." },
  ],
  author: {
    slug: "james-h-rivers",
    name: "James H. Rivers",
    credentialLine: "Founder, KnowThisWell",
  },
  youtubeStatus: "not-started",
  youtubeUrl: "",
  draft: false,
};

export default function Post() {
  return (
    <>
      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Key Takeaways</h2>
      <KeyTakeaways
        points={[
          "A sequence is an ordered list of numbers following a consistent rule — the two most common types are arithmetic (constant addition) and geometric (constant multiplication).",
          "An nth term formula lets you jump directly to any term's value by its position, without listing out every term that comes before it.",
          "Arithmetic sequences grow at a steady, linear rate; geometric sequences grow (or shrink) exponentially, which is why compound interest and viral spread follow geometric patterns, not arithmetic ones.",
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">The concept</h2>
      <ModeToggle
        labels={{ plain: "Plain", detailed: "Detailed" }}
        plain={<div className="prose-p">A <TermLink href="/math-numbers/sequences-and-patterns">sequence</TermLink> is just an ordered list of numbers that follows a rule, like 2, 5, 8, 11, 14 (add 3 each time) or 3, 6, 12, 24, 48 (double each time). The first kind — where you always add the same amount — is called an <TermLink href="/math-numbers/sequences-and-patterns">arithmetic sequence</TermLink>. The second kind — where you always multiply by the same amount — is called a <TermLink href="/math-numbers/sequences-and-patterns">geometric sequence</TermLink>. Spotting which type a pattern is tells you immediately how to predict any future term without writing out the whole list.</div>}
        detailed={<div className="prose-p">In an arithmetic sequence, each <TermLink href="/math-numbers/sequences-and-patterns">term</TermLink> is the previous term plus a fixed <TermLink href="/math-numbers/sequences-and-patterns">common difference</TermLink>, d. Rather than adding d repeatedly to reach, say, the 50th term, the <TermLink href="/math-numbers/sequences-and-patterns">nth term formula</TermLink> gives it directly: aₙ = a₁ + (n - 1)d, where a₁ is the first term and n is the position you want. In a geometric sequence, each term is the previous term multiplied by a fixed <TermLink href="/math-numbers/sequences-and-patterns">common ratio</TermLink>, r, and its nth term formula is aₙ = a₁ × r^(n-1). The structural difference between these two formulas — n multiplied by d in one, versus n as an exponent on r in the other — is exactly why arithmetic sequences plot as a straight line (linear growth) while geometric sequences plot as a rapidly curving graph (exponential growth or decay), even when their first few terms look deceptively similar in size.</div>}
      />
      <FootnoteAside>An old legend claims the inventor of chess was offered any reward by a grateful king and asked for wheat: 1 grain on the first chessboard square, 2 on the second, 4 on the third, doubling each time. By the 64th square alone the geometric sequence demands over 9 quintillion grains — more wheat than has likely ever been harvested in human history, illustrating just how fast geometric growth outpaces arithmetic growth.</FootnoteAside>

      <p>
      The formulas look abstract until you use them to skip straight to a distant term instead of grinding through every step to get there — that shortcut is the entire point of having an nth term formula in the first place.
      </p>

      <QuickCheck
        question="A sequence starts 5, 8, 11, 14, ... What type of sequence is this, and what is the common difference?"
        options={[
          { text: "Geometric, with a common ratio of 3", correct: false, explanation: "The terms aren't being multiplied by a constant factor (8 ÷ 5 is not the same as 14 ÷ 11) — they're increasing by a fixed amount instead, which is the signature of an arithmetic, not geometric, sequence." },
          { text: "Arithmetic, with a common difference of 3", correct: true, explanation: "Correct. Each term is 3 more than the one before it (5+3=8, 8+3=11, 11+3=14) — a constant amount being added is exactly what defines an arithmetic sequence." },
          { text: "Neither — this sequence doesn't follow a consistent rule", correct: false, explanation: "It does follow a consistent, simple rule: add 3 to each term to get the next one. That's the definition of an arithmetic sequence with common difference 3." },
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Worked examples</h2>

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 1: Finding the 20th term of an arithmetic sequence (baseline case)</h3>
      <div className="prose-p">
      A sequence starts at 4 and has a common difference of 6: 4, 10, 16, 22, ... Using aₙ = a₁ + (n - 1)d with a₁ = 4, d = 6, and n = 20: a₂₀ = 4 + (20 - 1)(6) = 4 + (19)(6) = 4 + 114 = <strong>118</strong>. Notice this took one calculation instead of listing out and adding to all 19 previous terms — that&apos;s the entire value of having a direct nth term formula.
      </div>

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 2: A geometric sequence with a fractional common ratio (edge case / variation)</h3>
      <div className="prose-p">
      A ball is dropped and bounces to 60% of its previous height each time. Starting at 200 cm, the sequence of bounce heights is 200, 120, 72, 43.2, ... — a geometric sequence with a₁ = 200 and common ratio r = 0.6 (a ratio less than 1, since the sequence is shrinking, not growing). Find the height of the 6th bounce: a₆ = 200 × 0.6^(6-1) = 200 × 0.6⁵ = 200 × 0.07776 = <strong>15.55 cm</strong>. A common ratio between 0 and 1 is a genuine, normal case — geometric sequences don&apos;t require growth, and a shrinking geometric sequence like this one approaches (but mathematically never quite reaches) zero.
      </div>

      <QuickCheck
        question="A sequence is 81, 27, 9, 3, ... What is the common ratio, and what is the next term?"
        options={[
          { text: "Common ratio of 1/3, next term is 1", correct: true, explanation: "Correct. Each term is one-third of the previous one (81 × 1/3 = 27, 27 × 1/3 = 9, 9 × 1/3 = 3), so the next term is 3 × 1/3 = 1." },
          { text: "Common difference of -54, next term is -51", correct: false, explanation: "The gap between terms isn't constant (81 to 27 is a difference of -54, but 27 to 9 is only -18) — this rules out an arithmetic sequence. It's geometric, defined by a ratio, not a difference." },
          { text: "Common ratio of 3, next term is 9", correct: false, explanation: "The sequence is shrinking, not growing, so the ratio must be less than 1 (specifically 1/3), not 3. Multiplying by 3 would make each term larger, which contradicts the pattern shown." },
        ]}
      />

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 3: Stadium seating rows (real-world / applied case)</h3>
      <p>
      A stadium section has 22 seats in the front row, and each row behind it has 4 more seats than the row in front. This is an arithmetic sequence with a₁ = 22 and d = 4. How many seats are in row 15? a₁₅ = 22 + (15 - 1)(4) = 22 + 56 = <strong>78 seats</strong>. Architects and event planners use exactly this kind of sequence to calculate total capacity and plan row-by-row seat numbering without physically counting every seat in every row — arithmetic sequences show up anywhere a quantity changes by a fixed, predictable amount per step: stacked shipping containers, loan payments with fixed extra principal, or evenly spaced utility poles along a road.
      </p>

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">How it works (visual)</h2>
      <DiagramBlock
        title="Arithmetic (linear) growth vs. geometric (exponential) growth"
        type="detail"
        svgSrc="/diagrams/math-numbers-sequences-and-patterns-arithmetic-vs-geometric-growth.svg"
        altText="A line graph with sequence position on the horizontal axis and term value on the vertical axis, showing two plotted sequences starting near the same point: a straight rising line labeled arithmetic sequence (constant difference) and a curve that starts similarly but bends sharply upward labeled geometric sequence (constant ratio), with the geometric curve visibly overtaking the arithmetic line after a few terms."
      />
      <p>
      Both sequences can start out looking similar for their first few terms, but the shapes diverge fast: the arithmetic sequence&apos;s straight line reflects the same fixed amount being added every step, while the geometric sequence&apos;s curve reflects each term being multiplied by the same factor — and multiplication compounds in a way addition never does, which is why the geometric curve eventually rockets past the arithmetic line no matter how large the arithmetic sequence&apos;s common difference is.
      </p>

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Common mistakes</h2>
      <MistakeList
        items={[
          { mistake: "Mixing up common difference and common ratio, or applying an arithmetic formula to a geometric sequence (or vice versa).", fix: "Check the sequence first: if consecutive terms have a constant difference, it's arithmetic (use +d). If they have a constant ratio (divide consecutive terms), it's geometric (use ×r)." },
          { mistake: "Off-by-one errors in the nth term formula, such as using n instead of (n - 1) as the exponent or multiplier.", fix: "Remember the first term a₁ requires zero applications of d or r — plug n = 1 into aₙ = a₁ + (n-1)d and confirm it returns exactly a₁ before trusting the formula for larger n." },
          { mistake: "Assuming a sequence must keep increasing forever.", fix: "Sequences can decrease (negative common difference, or a ratio between 0 and 1) or alternate in sign (a negative common ratio) — 'sequence' just means an ordered, rule-based list, with no requirement to grow." },
        ]}
      />
      <MisconceptionCallout
        myth="If a sequence's early terms are increasing, it must be geometric, since geometric sequences 'grow faster.'"
        reality={<p>Both arithmetic and geometric sequences can increase, decrease, or stay flat — the type depends entirely on how each term relates to the one before it (addition vs. multiplication), not on whether the sequence happens to be climbing. An arithmetic sequence like 3, 7, 11, 15 grows steadily by adding 4 each time; a geometric sequence like 20, 10, 5, 2.5 shrinks by multiplying by 0.5 each time. The only reliable test is to check whether consecutive terms share a constant difference (arithmetic) or a constant ratio (geometric) — appearance and direction alone can&apos;t tell you which type you&apos;re looking at.</p>}
      />

      <QuickCheck
        question="A sequence is 100, 90, 80, 70, ... — it's decreasing. Does this mean it must be an arithmetic sequence, since geometric sequences only decrease when shrinking toward zero via multiplication?"
        options={[
          { text: "Not necessarily from 'decreasing' alone — you have to check whether consecutive terms share a constant difference or a constant ratio", correct: true, explanation: "Correct. This particular sequence is arithmetic (constant difference of -10), but decreasing alone doesn't prove that — a geometric sequence with a ratio between 0 and 1, like 100, 50, 25, 12.5, also decreases." },
          { text: "Yes — any decreasing sequence is automatically arithmetic", correct: false, explanation: "This isn't true. Geometric sequences can decrease too, whenever the common ratio is between 0 and 1 (or negative) — decreasing behavior alone doesn't identify the type." },
          { text: "Yes — geometric sequences can only ever increase, never decrease", correct: false, explanation: "Geometric sequences absolutely can decrease — any common ratio between 0 and 1 produces a shrinking sequence, like 100, 50, 25, 12.5, which is geometric despite decreasing." },
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Try it yourself</h2>
      <EntryCalculator
        title="Arithmetic sequence: find the nth term (aₙ = a₁ + (n-1)d)"
        fields={[
          { key: "firstTerm", label: "First term (a₁)", defaultValue: 4 },
          { key: "commonDifference", label: "Common difference (d)", defaultValue: 6 },
          { key: "n", label: "Term position (n)", defaultValue: 20 },
        ]}
        resultLabel="Value of the nth term"
        formula="arithmeticSequenceNthTerm"
        formatResult="number"
      />
      <EntryCalculator
        title="Geometric sequence: find the nth term (aₙ = a₁ × r^(n-1))"
        fields={[
          { key: "firstTerm", label: "First term (a₁)", defaultValue: 200 },
          { key: "commonRatio", label: "Common ratio (r)", defaultValue: 0.6, step: 0.01 },
          { key: "n", label: "Term position (n)", defaultValue: 6 },
        ]}
        resultLabel="Value of the nth term"
        formula="geometricSequenceNthTerm"
        formatResult="number"
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">What to do next</h2>
      <ActionChecklist
        items={[
          "Take any sequence you notice in real life (savings growing at a fixed deposit per month, a bouncing ball, a discount that repeats) and identify whether it's arithmetic or geometric.",
          "Use the arithmetic calculator above to find a term far out (like the 100th term) and notice how much faster it is than adding step by step.",
          "Compare the geometric calculator's output at n = 5 versus n = 10 for the same starting values to see exponential growth accelerate firsthand.",
          "Read the related entry on Linear Equations Explained to see how an arithmetic sequence's nth term formula is really just a linear equation in disguise.",
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">FAQ</h2>
      <FAQBlock
        items={[
          { question: "What is the difference between an arithmetic and a geometric sequence?", answer: "An arithmetic sequence adds a fixed amount (the common difference) to get each next term. A geometric sequence multiplies by a fixed amount (the common ratio) instead — addition versus multiplication is the entire distinction." },
          { question: "How do you find the nth term of a sequence without listing every term?", answer: "Use the nth term formula: aₙ = a₁ + (n-1)d for an arithmetic sequence, or aₙ = a₁ × r^(n-1) for a geometric sequence, where a₁ is the first term and n is the position you want." },
          { question: "Can a sequence be both arithmetic and geometric?", answer: "Only in the trivial case where every term is identical (a constant sequence, common difference 0 and common ratio 1). Any sequence that actually changes value follows one pattern or the other, not both." },
          { question: "Why do geometric sequences grow faster than arithmetic sequences?", answer: "Arithmetic sequences add the same fixed amount every step (linear growth), while geometric sequences multiply by the same factor every step (exponential growth). Multiplication compounds on itself in a way repeated addition never does, so a geometric sequence eventually outpaces any arithmetic sequence, however large its common difference." },
          { question: "What is a real-life example of a geometric sequence?", answer: "Compound interest is a classic example — a balance multiplied by the same growth factor every period. Bouncing ball heights, radioactive decay, and viral content sharing (if each person shares with a fixed number of new people) are other common real-world geometric sequences." },
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Related terms</h2>
      <GlossaryStrip terms={metadata.glossary ?? []} />
      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">See also</h2>
      <SeeAlsoList slugs={metadata.seeAlso ?? []} />
    </>
  );
}
