import React from 'react';
import { PostFrontmatter } from '@/types/post';
import {
  KeyTakeaways,
  ModeToggle,
  FootnoteAside,
  QuickCheck,
  DiagramBlock,
  MistakeList,
  MisconceptionCallout,
  ActionChecklist,
  FAQBlock,
  GlossaryStrip,
  SeeAlsoList,
  TermLink,
} from '@/components';

export const metadata: PostFrontmatter = {
  title: "Two-Factor Authentication Explained: Why a Password Alone Isn't Enough",
  category: "technology-basics",
  order: 52,
  subtopic: "cybersecurity-literacy-basics",
  tags: ["two-factor authentication", "2FA", "multi-factor authentication", "account security", "cybersecurity basics"],
  date: "2026-08-28",
  updated: "2026-08-28",
  lastReviewed: "2026-08-28",
  excerpt: "Two-factor authentication requires two independent kinds of proof, not just a stronger password — so a stolen password alone still isn't enough to get in.",
  summary: "Two-factor authentication (2FA) requires a person to prove their identity with two independent types of evidence — typically something they know, like a password, plus something they have or are — so that a stolen password alone is not enough to access an account.",
  sources: [
    { label: "CISA — Require Multifactor Authentication", url: "https://www.cisa.gov/secure-our-world/require-multifactor-authentication" },
    { label: "NIST Special Publication 800-63B — Digital Identity Guidelines: Authentication and Lifecycle Management", url: "https://pages.nist.gov/800-63-3/sp800-63b.html" },
    { label: "OWASP Cheat Sheet Series — Multifactor Authentication Cheat Sheet", url: "https://cheatsheetseries.owasp.org/cheatsheets/Multifactor_Authentication_Cheat_Sheet.html" },
  ],
  seeAlso: [
    "technology-basics/what-a-password-manager-actually-does",
    "technology-basics/why-strong-passwords-actually-matter",
    "technology-basics/what-a-data-breach-actually-means-for-you",
  ],
  glossary: [
    { term: "Two-factor authentication (2FA)", definition: "A login process requiring two independent categories of proof of identity — commonly a password plus a one-time code or physical device — instead of a password alone." },
    { term: "Authentication factor", definition: "One of three recognized categories of identity proof: something you know (a password), something you have (a phone or security key), or something you are (a fingerprint or face scan)." },
    { term: "One-time passcode (OTP)", definition: "A short numeric code that is valid for only a single login attempt and typically expires within seconds to minutes, generated by an app or sent by text message." },
    { term: "Phishing-resistant authentication", definition: "A form of multi-factor authentication, such as a hardware security key, that cryptographically verifies the exact website being logged into, so it cannot be tricked by a convincing but fake copy of that site." },
  ],
  author: {
    slug: "james-h-rivers",
    name: "James H. Rivers",
    credentialLine: "Founder, KnowThisWell",
  },
  youtubeStatus: "not-started",
  youtubeUrl: "",
  draft: false,
};

export default function Post() {
  return (
    <>
      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Key Takeaways</h2>
      <KeyTakeaways
        points={[
          "Two-factor authentication requires two independent categories of proof — commonly something you know (a password) and something you have (a phone or security key) — not just a longer or harder password.",
          "Because the two factors are independent, an attacker who steals only the password still can't get in without also possessing the second factor, which is the entire point of the design.",
          "Not all second factors offer equal protection — a text-message code is better than nothing, but a hardware security key or authenticator app resists a wider range of attacks, including certain phishing techniques.",
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">The concept</h2>
      <ModeToggle
        labels={{ plain: "Plain", detailed: "Detailed" }}
        plain={<div className="prose-p">Getting into a safe deposit box at a bank usually needs two separate keys — yours and the bank&apos;s — and neither one works alone. <TermLink href="/technology-basics/two-factor-authentication-explained">Two-factor authentication</TermLink> works the same way for an online account: your password is one key, and a second, different kind of proof (a code from your phone, a fingerprint, a physical security key) is the other. A thief who only gets your password is stuck holding one key to a lock that needs two.</div>}
        detailed={<div className="prose-p">This is a direct application of the <strong>trust chain / verification</strong> mental model: a system shouldn&apos;t grant access on a single unverified claim, but on a chain of independently checkable proofs. Security literature groups proof into three <TermLink href="/technology-basics/two-factor-authentication-explained">authentication factors</TermLink>: something you know (a password or PIN), something you have (a phone, a hardware key), and something you are (a fingerprint or face scan). Genuine two-factor authentication combines proofs from <em>two different categories</em> — a password plus a fingerprint counts; a password plus a security question does not, since both are &quot;something you know.&quot; The edge case that matters: not all second factors resist the same attacks. A text-message <TermLink href="/technology-basics/two-factor-authentication-explained">one-time passcode</TermLink> can, in rare cases, be intercepted through a SIM-swap attack on the phone carrier; a hardware security key using <TermLink href="/technology-basics/two-factor-authentication-explained">phishing-resistant authentication</TermLink> cryptographically checks the actual website address, so it can&apos;t be fooled by a convincing fake login page the way a typed-in code can.</div>}
      />
      <FootnoteAside>NIST SP 800-63B formally defines three Authenticator Assurance Levels (AAL1–AAL3), each requiring progressively stronger combinations of factors — AAL3 specifically requires a hardware-based authenticator resistant to phishing, which is why some sensitive systems mandate a physical security key rather than accepting a text-message code.</FootnoteAside>

      <p>
        Once you see it as two independent checks instead of one stronger one, the rest follows: why a stolen password isn&apos;t enough on its own, and why some second factors are meaningfully more resistant to attack than others.
      </p>

      <QuickCheck
        question="A login system asks for a password, and then asks the user to answer a security question they set up earlier (like their mother's maiden name). Is this genuine two-factor authentication?"
        options={[
          { text: "Yes, because it requires two separate pieces of information", correct: false, explanation: "Requiring two pieces of information isn't the same as requiring two independent factor categories. A security question is still 'something you know,' the same category as the password." },
          { text: "No, because both the password and the security question fall into the same authentication factor category ('something you know')", correct: true, explanation: "Correct. Genuine two-factor authentication requires proofs from two different categories — something you know plus something you have or are — not two pieces of knowledge-based information." },
          { text: "No, because two-factor authentication always requires a physical device", correct: false, explanation: "A physical device (something you have) is one common second factor, but biometrics (something you are) also qualify. The requirement is a second, different category — not specifically a device." },
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Worked examples</h2>

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 1: Logging in with a password and an authenticator app code (baseline case)</h3>
      <div className="prose-p">
        Someone enters their password on a login page, which is accepted, and the site then asks for a six-digit code from an authenticator app on their phone. The app generates a new code every 30 seconds using a secret it shares only with that account, so even someone who correctly guessed or stole the password would also need physical access to the unlocked phone and its app within that same 30-second window — two independent conditions that have to both be true at once.
      </div>
      <QuickCheck
        question="Why does requiring a code from an authenticator app meaningfully improve security over a password alone, even if an attacker already knows the correct password?"
        options={[
          { text: "Because the app's code changes constantly and is generated locally on a device the account owner physically holds, so knowing the password alone isn't sufficient to produce a valid code", correct: true, explanation: "Correct. The attacker would separately need access to the physical device generating the code, which is an independent requirement from knowing the password." },
          { text: "Because authenticator app codes never expire, so they're more convenient to reuse", correct: false, explanation: "The opposite is true — authenticator app codes are deliberately short-lived (commonly 30 seconds), which is part of what makes them hard to intercept and reuse later." },
          { text: "Because the authenticator app replaces the need for a password entirely", correct: false, explanation: "In standard two-factor authentication, the app supplies the second factor in addition to the password — it doesn't replace the password requirement." },
        ]}
      />

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 2: A SIM-swap attack targeting a text-message code (edge case / variation)</h3>
      <div className="prose-p">
        An attacker who already has someone&apos;s password convinces a phone carrier, through social engineering, to transfer that person&apos;s phone number onto a SIM card the attacker controls. Once that succeeds, text-message codes meant for the real owner are delivered to the attacker instead, defeating that specific second factor. This is a real, documented weakness of SMS-based codes specifically — it doesn&apos;t apply to an authenticator app or hardware key, since those aren&apos;t tied to a phone number a carrier can be tricked into reassigning.
      </div>
      <QuickCheck
        question="A SIM-swap attack can defeat which type of two-factor authentication, and why doesn't it affect an authenticator app in the same way?"
        options={[
          { text: "It can defeat text-message (SMS) codes, because those are delivered to whatever phone number the carrier currently has assigned, which a SIM swap can redirect; an authenticator app's codes are generated locally on the device and aren't tied to the phone carrier at all", correct: true, explanation: "Correct. The vulnerability is specific to how SMS routes through the carrier's number assignment — a locally generated app code has no such dependency." },
          { text: "It can defeat any form of two-factor authentication equally, since all methods rely on a phone", correct: false, explanation: "Not all second factors rely on a phone number at all — hardware security keys and some authenticator apps don't depend on carrier-assigned phone numbers, so SIM-swapping doesn't affect them." },
          { text: "It can defeat authenticator apps but not text messages", correct: false, explanation: "It's the reverse — SIM-swapping exploits the phone carrier's number reassignment, which affects SMS delivery specifically, not locally generated authenticator app codes." },
        ]}
      />

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 3: An organization requiring phishing-resistant hardware keys for sensitive access (real-world / applied case)</h3>
      <p>
        A workplace that handles particularly sensitive systems requires employees to use a physical hardware security key, rather than a text-message or app code, to log in. The key uses cryptography that checks the exact website address being logged into as part of the verification, so even if an employee is tricked into visiting a convincing fake login page, the key won&apos;t complete the authentication there — because the fake page&apos;s address doesn&apos;t cryptographically match what the key expects. This is the specific property NIST calls phishing-resistant authentication, and it&apos;s why some organizations mandate it for their highest-risk accounts specifically, rather than treating all forms of two-factor authentication as equally strong.
      </p>
      <QuickCheck
        question="Why might an organization specifically require a hardware security key instead of accepting a text-message code for its most sensitive accounts?"
        options={[
          { text: "Because hardware keys are the only form of two-factor authentication that works without an internet connection", correct: false, explanation: "Connectivity isn't the distinguishing factor here — the key advantage of a hardware key in this scenario is that it verifies the actual site address, resisting a category of phishing attack that a typed-in code can't." },
          { text: "Because a hardware key cryptographically verifies the real website's address, so it won't authenticate on a convincing fake login page the way a manually typed code could be tricked into being entered", correct: true, explanation: "Correct. This 'phishing-resistant' property is exactly why NIST treats hardware-based authenticators as meeting a higher assurance level than codes a person types in manually." },
          { text: "Because hardware keys don't require the user to also know a password", correct: false, explanation: "Hardware keys are typically used as one factor alongside a password (or as part of passwordless login flows), not as a way to skip password verification for standard two-factor setups." },
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">How it works (visual)</h2>
      <DiagramBlock
        title="Two independent proofs, checked in sequence"
        type="flow"
        svgSrc="/diagrams/technology-basics-two-factor-authentication-explained-verification-flow.svg"
        altText="A sequence diagram showing a login attempt in two steps: step one checks something the user knows, a password, against the server; step two requests something the user separately has, such as a code from a phone app, before granting access, with a rejected branch showing that a correct password alone does not grant access."
      />
      <p>
        Each step is a separate checkpoint with its own failure mode — passing the first doesn&apos;t shortcut the second, which is precisely what stops a stolen password from being sufficient on its own.
      </p>

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Common mistakes</h2>
      <MistakeList
        items={[
          { mistake: "Treating a security question as a genuine second factor.", fix: "Recognize that a security question is still 'something you know,' the same category as a password — real 2FA needs a second, different category, like a device or a biometric." },
          { mistake: "Assuming all forms of two-factor authentication offer the same protection.", fix: "Understand that text-message codes, while much better than a password alone, are more vulnerable to SIM-swap attacks than an authenticator app or hardware security key." },
          { mistake: "Turning 2FA on for a login but ignoring the account's recovery/backup codes.", fix: "Save the backup codes generated when you enable 2FA somewhere safe — losing both your password and your second-factor device with no backup code can lock you out of your own account." },
        ]}
      />
      <MisconceptionCallout
        myth="Two-factor authentication makes an account impossible to break into."
        reality={<p>Two-factor authentication makes a stolen password alone insufficient — a major, real improvement — but it isn&apos;t an absolute guarantee. Certain second factors (text-message codes especially) have documented weaknesses like SIM-swap attacks, and some phishing techniques can prompt a person to hand over a one-time code in real time. It substantially raises the difficulty of unauthorized access; it doesn&apos;t make it theoretically impossible.</p>}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">What to do next</h2>
      <ActionChecklist
        items={[
          "Turn on two-factor authentication for email, banking, and any account that offers it — email especially, since it's often the recovery path into everything else.",
          "Prefer an authenticator app or hardware security key over a text-message code where the option exists, since both resist SIM-swap attacks.",
          "Save the backup/recovery codes generated when you enable 2FA somewhere safe, before you ever need them.",
          "Never read a one-time code out loud to someone who contacted you unexpectedly, even if they claim to be from the company itself — a legitimate provider never needs you to say the code to them.",
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">FAQ</h2>
      <FAQBlock
        items={[
          { question: "What is two-factor authentication?", answer: "A login process requiring two independent categories of identity proof — typically something you know, like a password, plus something you have or are, like a phone-generated code or a fingerprint — so a password alone isn't sufficient to access the account." },
          { question: "Is two-factor authentication the same as multi-factor authentication (MFA)?", answer: "Two-factor authentication is a specific case of multi-factor authentication using exactly two factors. MFA is the broader term, which can include two or more independent factors." },
          { question: "Is text-message (SMS) two-factor authentication safe to use?", answer: "It's significantly safer than no second factor at all, but it has a documented weakness: SIM-swap attacks, where an attacker convinces a carrier to reassign a phone number, can intercept SMS codes. Authenticator apps and hardware keys avoid this specific weakness." },
          { question: "Why does my bank ask for a code even after I enter the right password?", answer: "That code is the second authentication factor. It confirms you also possess a separate device or app tied to the account, so someone who obtained only your password still can't complete the login." },
          { question: "What happens if I lose the phone my two-factor authentication depends on?", answer: "Most services provide backup or recovery codes generated when you first set up 2FA specifically for this situation — saving those codes somewhere safe in advance is the standard way to avoid being locked out." },
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Related terms</h2>
      <GlossaryStrip terms={metadata.glossary ?? []} />
      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">See also</h2>
      <SeeAlsoList slugs={metadata.seeAlso ?? []} />
    </>
  );
}
