import React from 'react';
import { PostFrontmatter } from '@/types/post';
import {
  KeyTakeaways,
  ModeToggle,
  FootnoteAside,
  QuickCheck,
  DiagramBlock,
  MistakeList,
  MisconceptionCallout,
  ActionChecklist,
  FAQBlock,
  GlossaryStrip,
  SeeAlsoList,
  TermLink
} from '@/components';

export const metadata: PostFrontmatter = {
  title: "What Two-Factor Authentication Actually Does",
  category: "digital-safety-privacy",
  order: 2,
  subtopic: "everyday-account-security",
  tags: ["two-factor authentication", "2FA", "MFA", "account security", "password"],
  date: "2026-09-21",
  updated: "2026-09-21",
  lastReviewed: "2026-09-21",
  excerpt: "A stolen password alone stops opening the door once a second, separate proof is required — that's the entire point of two-factor authentication.",
  summary: "Two-factor authentication (2FA) requires two different categories of proof before granting account access — typically something you know (a password) plus something you have (a code from an app or device) or something you are (a fingerprint) — so that a stolen or guessed password alone is no longer enough to log in, because an attacker would also need to separately compromise the second, independent factor.",
  sources: [
    { label: "CISA — Turn On Multifactor Authentication", url: "https://www.cisa.gov/secure-our-world/turn-multifactor-authentication" },
    { label: "NIST Special Publication 800-63B — Digital Identity Guidelines", url: "https://pages.nist.gov/800-63-3/" },
  ],
  seeAlso: [
    "digital-safety-privacy/how-password-managers-actually-protect-you",
    "digital-safety-privacy/how-antivirus-software-actually-detects-threats",
    "technology-basics/end-to-end-encryption-explained",
  ],
  glossary: [
    { term: "Authentication factor", definition: "One of three general categories of proof used to verify identity: something you know (a password), something you have (a phone or security key), or something you are (a fingerprint or face scan)." },
    { term: "One-time code", definition: "A short numeric code, valid for a single login attempt or a brief time window, generated by an authenticator app or sent to a registered device." },
    { term: "Credential stuffing", definition: "An attack where a list of usernames and passwords stolen from one breached service is automatically tried against many other services, exploiting reused passwords." },
  ],
  author: {
    slug: "james-h-rivers",
    name: "James H. Rivers",
    credentialLine: "Founder, KnowThisWell",
  },
  youtubeStatus: "not-started",
  youtubeUrl: "",
  draft: false,
};

export default function Post() {
  return (
    <>
      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Key Takeaways</h2>
      <KeyTakeaways
        points={[
          "Two-factor authentication requires two different categories of proof — typically a password plus a code or device — before granting access.",
          "It's specifically designed to stop the most common real-world attack: a stolen or reused password being used to log in from an attacker's device.",
          "Per CISA and NIST guidance, an authenticator app or hardware key is generally more resistant to interception than a text-message code, though any 2FA is far better than none.",
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">The concept</h2>
      <ModeToggle
        labels={{ plain: "Plain", detailed: "Detailed" }}
        plain={<div className="prose-p">Two-factor authentication means logging in takes two separate proofs instead of just a password. Usually that&apos;s your password plus a short code from an app on your phone. If someone steals or guesses your password alone, they still can&apos;t get in, because they don&apos;t have the second piece — your phone or app.</div>}
        detailed={<div className="prose-p">Per CISA and NIST SP 800-63B guidance, security professionals group login proof into three <TermLink href="/digital-safety-privacy/what-two-factor-authentication-actually-does">authentication factor</TermLink> categories: something you know (a password or PIN), something you have (a phone, authenticator app, or hardware security key), and something you are (biometrics like a fingerprint). A single password is &quot;one factor.&quot; Two-factor authentication (2FA) requires proof from two different categories — almost always &quot;know&quot; plus &quot;have.&quot; This matters because the most common real-world account compromise isn&apos;t a sophisticated hack of the service itself — it&apos;s <TermLink href="/digital-safety-privacy/what-two-factor-authentication-actually-does">credential stuffing</TermLink>, where a password leaked from one breached site is tried against many other sites, exploiting people who reuse passwords. 2FA breaks that attack cold, because the attacker has the password but not the second factor. NIST guidance specifically notes that SMS text-message codes, while far better than no 2FA, are more vulnerable to interception (for example, through SIM-swapping) than an authenticator app&apos;s <TermLink href="/digital-safety-privacy/what-two-factor-authentication-actually-does">one-time code</TermLink> or a physical hardware security key, which don&apos;t rely on the phone network at all.</div>}
      />
      <FootnoteAside>CISA&apos;s own guidance frames turning on multifactor authentication as one of the single highest-impact actions an individual can take for account security — a small amount of login friction in exchange for closing off the most common real-world attack path.</FootnoteAside>

      <p>This is also why a data breach notice for one account should prompt checking every other account using the same password, not just changing the one that was breached — reused passwords are exactly what credential stuffing exploits.</p>

      <QuickCheck
        question="An attacker obtains someone's correct password from a breached, unrelated website. The person had 2FA enabled with an authenticator app on their main email account. What happens if the attacker tries to log in?"
        options={[
          { text: "The login attempt fails without the second factor, since the attacker only has the password, which is one of two required proofs", correct: true, explanation: "Correct. This is exactly the attack 2FA is designed to stop — a correct password alone isn't sufficient once a second, independent factor is required." },
          { text: "The login succeeds because the password was correct", correct: false, explanation: "With 2FA properly enabled, a correct password alone is not sufficient — the second factor is a separate, required check." },
          { text: "The account gets automatically locked regardless of 2FA status", correct: false, explanation: "Account lockout policies vary by service and aren't what stops this specific attack — the second-factor requirement itself is what blocks the login." },
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Worked examples</h2>

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 1: Logging into a bank account with an authenticator app (baseline case)</h3>
      <div className="prose-p">After entering the correct password, the site prompts for a 6-digit code from an authenticator app on the person&apos;s phone — the code changes every 30 seconds and is generated locally on the device, so it can&apos;t be reused later even if it were somehow observed.</div>

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 2: SMS 2FA versus a SIM-swap attack (edge case / variation)</h3>
      <div className="prose-p">Per NIST&apos;s noted concerns, if a text-message-based second factor is used and an attacker successfully convinces a mobile carrier to transfer the victim&apos;s phone number to a new SIM card (a SIM-swap), the attacker can receive the SMS code themselves — a real, documented weakness that an app-based or hardware-key second factor doesn&apos;t share, since neither depends on the phone network.</div>

      <h3 className="scroll-mt-10 font-display text-xl font-bold text-ink mb-4">Example 3: A hardware security key at a workplace (real-world / applied case)</h3>
      <div className="prose-p">Many organizations, following CISA guidance, issue physical security keys that must be physically plugged in or tapped to complete a login — this is a &quot;something you have&quot; factor that can&apos;t be phished remotely the way a typed code can, since there&apos;s no code for an attacker to trick someone into revealing.</div>

      <QuickCheck
        question="Why does NIST guidance note that SMS-based 2FA codes are more vulnerable than an authenticator app or hardware key?"
        options={[
          { text: "SMS codes depend on the phone network, which can be intercepted through attacks like SIM-swapping, while app-based and hardware-key methods don't rely on the phone network", correct: true, explanation: "Correct. The dependency on carrier infrastructure is the specific weakness — app-based and hardware-key methods generate or verify the second factor independently of the phone network." },
          { text: "SMS codes are technically identical in security to app-based codes", correct: false, explanation: "NIST guidance specifically distinguishes them — SMS is noted as more vulnerable to interception, not equivalent." },
          { text: "SMS 2FA doesn't actually require a second factor at all", correct: false, explanation: "SMS 2FA is still a genuine second factor (something you have — access to the phone number); the concern is about how that factor can be intercepted, not whether it counts as one." },
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">How it works (visual)</h2>
      <DiagramBlock
        title="Why a stolen password alone isn't enough with 2FA on"
        type="flow"
        svgSrc="/diagrams/digital-safety-privacy-what-two-factor-authentication-actually-does-flow.svg"
        altText="A flow diagram: a login attempt with a correct password reaches a second checkpoint requiring a one-time code or hardware key; without that second factor, access is denied even though the password was correct."
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Common mistakes</h2>
      <MistakeList
        items={[
          { mistake: "Assuming a strong, unique password alone is enough protection.", fix: "Enable 2FA wherever it's offered, especially on email, banking, and any account used to reset other accounts." },
          { mistake: "Treating all 2FA methods as equally secure.", fix: "Prefer an authenticator app or hardware key over SMS text codes where the option exists, per NIST guidance on SIM-swap risk." },
          { mistake: "Approving an unexpected 2FA push notification without checking if you actually initiated the login.", fix: "Deny and investigate any 2FA prompt you didn't trigger yourself — it usually means someone already has your password." },
        ]}
      />
      <MisconceptionCallout
        myth="Two-factor authentication is mostly a hassle that only adds friction without much real security benefit."
        reality={<p>Per CISA, enabling multifactor authentication is one of the highest-impact individual security actions available, because it directly defeats the most common real-world account compromise method — reused or breached passwords tried against other sites. A stolen password alone becomes useless against an account with 2FA enabled, which is a substantial, measurable security gain for a small amount of added login friction.</p>}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">What to do next</h2>
      <ActionChecklist
        items={[
          "Turn on 2FA for email, banking, and any account that can be used to reset other accounts' passwords — these are the highest-value targets to protect first.",
          "Where offered, choose an authenticator app or hardware security key over SMS text-message codes.",
          "Never approve a 2FA prompt you didn't personally trigger — treat it as a signal your password may be compromised.",
          "This is general security education, not a guarantee against every attack — for account compromise or suspected fraud, contact the affected service and, where financial accounts are involved, your financial institution directly.",
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">FAQ</h2>
      <FAQBlock
        items={[
          { question: "What does two-factor authentication actually protect against?", answer: "Primarily, it protects against a stolen, guessed, or breached password being used to log in — the second factor requirement means the password alone isn't sufficient." },
          { question: "Is SMS-based 2FA still worth using if it's not the most secure option?", answer: "Yes — per NIST and CISA guidance, any 2FA is substantially better than none, even if an authenticator app or hardware key is the stronger option where available." },
          { question: "Can 2FA be bypassed?", answer: "No security measure is absolute — sophisticated phishing and SIM-swap attacks exist — but 2FA meaningfully raises the difficulty and blocks the overwhelmingly common password-reuse attack path, per CISA guidance." },
          { question: "Is two-factor authentication the same thing as multi-factor authentication (MFA)?", answer: "2FA is a specific case of MFA using exactly two factors — MFA is the broader term covering two or more factors." },
          { question: "What should I do if I get a 2FA prompt I didn't request?", answer: "Deny it and change the account's password immediately — an unrequested 2FA prompt generally means someone else already has your correct password." },
        ]}
      />

      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">Related terms</h2>
      <GlossaryStrip terms={metadata.glossary ?? []} />
      <h2 className="scroll-mt-10 border-t-2 border-ink pt-3.5 mt-12 mb-4 font-display text-2xl font-bold text-ink">See also</h2>
      <SeeAlsoList slugs={metadata.seeAlso ?? []} />
    </>
  );
}
